/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfacez;

import ModeloColas.MM1Model;
import ModeloColas.Simulacion;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.net.URI;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import visual.Simulador;
import visual.Visitante;




/**
 *
 * @author RMerino
 */
public class Simulado extends javax.swing.JFrame {

    int n ;
    Double lamb;
    double Pn;
    double rho;
  
    
    /**
     * Creates new form Simulado
     */
    public Simulado() {
       initComponents();
        centrarVentana();
        transparenciaBotones();
      PanelImagen obj = new PanelImagen();
        obj.setImagen("principal1.jpg");
        this.add(obj, BorderLayout.CENTER);
        setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/xd-04.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rhoTxt = new javax.swing.JTextField();
        LTxt = new javax.swing.JTextField();
        wTxt = new javax.swing.JTextField();
        efiTxt = new javax.swing.JTextField();
        LqTxt = new javax.swing.JTextField();
        wqTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lambdaTxt = new javax.swing.JTextField();
        miuTxt = new javax.swing.JTextField();
        borrar1 = new javax.swing.JButton();
        simularBtn = new javax.swing.JButton();
        reg = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        wtTxt = new javax.swing.JTextField();
        tTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        borrar3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        t2Txt = new javax.swing.JTextField();
        wqtTxt = new javax.swing.JTextField();
        borrar4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBackground(new java.awt.Color(0, 204, 0));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RESULTADOS");

        jLabel5.setFont(new java.awt.Font("Ubuntu Light", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Intensidad:");

        jLabel6.setFont(new java.awt.Font("Ubuntu Light", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Eficiencia");

        jLabel7.setFont(new java.awt.Font("Ubuntu Light", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("L:");

        jLabel8.setFont(new java.awt.Font("Ubuntu Light", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lq:");

        jLabel9.setFont(new java.awt.Font("Ubuntu Light", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("W:");

        jLabel10.setFont(new java.awt.Font("Ubuntu Light", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Wq:");

        rhoTxt.setEditable(false);
        rhoTxt.setBackground(new java.awt.Color(0, 204, 0));
        rhoTxt.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        rhoTxt.setForeground(new java.awt.Color(255, 255, 255));
        rhoTxt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        rhoTxt.setAutoscrolls(false);
        rhoTxt.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        rhoTxt.setEnabled(false);
        rhoTxt.setMaximumSize(null);

        LTxt.setEditable(false);
        LTxt.setBackground(new java.awt.Color(0, 204, 0));
        LTxt.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        LTxt.setForeground(new java.awt.Color(255, 255, 255));
        LTxt.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        LTxt.setEnabled(false);

        wTxt.setEditable(false);
        wTxt.setBackground(new java.awt.Color(0, 204, 0));
        wTxt.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        wTxt.setForeground(new java.awt.Color(255, 255, 255));
        wTxt.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        wTxt.setEnabled(false);

        efiTxt.setEditable(false);
        efiTxt.setBackground(new java.awt.Color(0, 204, 0));
        efiTxt.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        efiTxt.setForeground(new java.awt.Color(255, 255, 255));
        efiTxt.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        efiTxt.setEnabled(false);

        LqTxt.setEditable(false);
        LqTxt.setBackground(new java.awt.Color(0, 204, 0));
        LqTxt.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        LqTxt.setForeground(new java.awt.Color(255, 255, 255));
        LqTxt.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        LqTxt.setEnabled(false);

        wqTxt.setEditable(false);
        wqTxt.setBackground(new java.awt.Color(0, 204, 0));
        wqTxt.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        wqTxt.setForeground(new java.awt.Color(255, 255, 255));
        wqTxt.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        wqTxt.setEnabled(false);
        wqTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wqTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(wTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rhoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(efiTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(LqTxt)
                            .addComponent(wqTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(efiTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rhoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LqTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(LTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wqTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INGRESAR PARAMETROS DE ENTRADA");

        jLabel2.setFont(new java.awt.Font("Ubuntu Light", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lambda (λ):");

        jLabel3.setFont(new java.awt.Font("Ubuntu Light", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Miu (μ):");

        lambdaTxt.setBackground(new java.awt.Color(0, 204, 0));
        lambdaTxt.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        lambdaTxt.setForeground(new java.awt.Color(255, 255, 255));
        lambdaTxt.setCaretColor(new java.awt.Color(255, 255, 255));
        lambdaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lambdaTxtActionPerformed(evt);
            }
        });

        miuTxt.setBackground(new java.awt.Color(0, 204, 0));
        miuTxt.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        miuTxt.setForeground(new java.awt.Color(255, 255, 255));

        borrar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        borrar1.setText("LIMPIAR");
        borrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar1ActionPerformed(evt);
            }
        });

        simularBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        simularBtn.setText("SIMULAR");
        simularBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simularBtn.setPreferredSize(new java.awt.Dimension(121, 42));
        simularBtn.setSelected(true);
        simularBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simularBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lambdaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(miuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simularBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borrar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(44, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lambdaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(simularBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(miuTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        reg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reg.setText("ATRAS");
        reg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });

        salir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        salir.setText("SALIR");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setSelected(true);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 204, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" ");

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        wtTxt.setBackground(new java.awt.Color(0, 204, 0));
        wtTxt.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        wtTxt.setForeground(new java.awt.Color(255, 255, 255));
        wtTxt.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        wtTxt.setEnabled(false);

        tTxt.setBackground(new java.awt.Color(0, 204, 0));
        tTxt.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        tTxt.setForeground(new java.awt.Color(255, 255, 255));
        tTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTxtActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Ubuntu Light", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("t:");

        jLabel15.setFont(new java.awt.Font("Ubuntu Light", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("W(t):");

        jLabel17.setBackground(new java.awt.Color(102, 255, 102));
        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TIEMPO MEDIO ESPERA EN SISTEMA (W)");

        borrar3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        borrar3.setText("LIMPIAR");
        borrar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(wtTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(tTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(borrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(tTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(borrar3)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("TIEMPO MEDIO ESPERA EN COLA (WQ)");

        jLabel19.setFont(new java.awt.Font("Ubuntu Light", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("t:");

        jLabel20.setFont(new java.awt.Font("Ubuntu Light", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Wq(t):");

        t2Txt.setBackground(new java.awt.Color(0, 204, 0));
        t2Txt.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        t2Txt.setForeground(new java.awt.Color(255, 255, 255));

        wqtTxt.setEditable(false);
        wqtTxt.setBackground(new java.awt.Color(0, 204, 0));
        wqtTxt.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        wqtTxt.setForeground(new java.awt.Color(255, 255, 255));
        wqtTxt.setDisabledTextColor(new java.awt.Color(0, 0, 51));
        wqtTxt.setEnabled(false);

        borrar4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        borrar4.setText("LIMPIAR");
        borrar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        borrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t2Txt, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(wqtTxt))
                        .addGap(18, 18, 18)
                        .addComponent(borrar4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(t2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wqtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(borrar4)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(584, 584, 584)
                        .addComponent(jLabel14))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel11.setText("PANADERIA SAN JUDAS");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel12.setText("SISTEMA DE COLAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reg, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(204, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(167, 167, 167)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg)
                    .addComponent(salir))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel12)
                    .addContainerGap(463, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        // TODO add your handling code here:
        String nom = "visitante";
        int numBotella = 100;
        Simulador obj = new Simulador(nom,numBotella);
        obj.setVisible(true);
        this.dispose();
        this.setDefaultCloseOperation(Visitante.EXIT_ON_CLOSE);
    }//GEN-LAST:event_regActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        if(JOptionPane.showConfirmDialog(null,"¿Desea Salir?", "Confirmación",JOptionPane.YES_NO_OPTION)==0){
            System.exit(0);
        }
    }//GEN-LAST:event_salirActionPerformed

    private void borrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar3ActionPerformed
        tTxt.setText("");
        wtTxt.setText("");
    }//GEN-LAST:event_borrar3ActionPerformed

    private void borrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar4ActionPerformed
        t2Txt.setText("");
        wqtTxt.setText("");
    }//GEN-LAST:event_borrar4ActionPerformed

    private void simularBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simularBtnActionPerformed
        // TODO add your handling code here:
       /* QUITAR INGRESO DE NUMERO DE CLIENTES 
        if("".equals(nClientesTxt.getText())|| "".equals(tTxt.getText())|| "".equals(t2Txt.getText())){
            JOptionPane.showMessageDialog(null, "Parametros faltantes  \n introducir los valores de t para W, Wq, y No de Clientes", "Sugerencia", JOptionPane.INFORMATION_MESSAGE);
        }

        if(!"".equals(nClientesTxt.getText())){
            MM1Model m = new MM1Model(Double.valueOf(lambdaTxt.getText()), Double.valueOf(miuTxt.getText()));
            Integer n = Integer.valueOf(nClientesTxt.getText());

            double rho = Double.parseDouble(lambdaTxt.getText() )/Double.parseDouble( miuTxt.getText());
            Pn = redondear(m.Pn(rho, Integer.valueOf(nClientesTxt.getText())), 5);
            probTxt.setText(String.valueOf(Pn));
        }*/

        if(validacion())
        {
            Simulacion s = new Simulacion(Double.parseDouble(lambdaTxt.getText()), Double.parseDouble(miuTxt.getText()), true);

            rhoTxt.setText(String.valueOf(redondear(s.getRho(), 4)));
            efiTxt.setText(String.valueOf(redondear(s.getEficiencia(), 4)));
            LTxt.setText(String.valueOf(redondear(s.getL(), 4)));
            LqTxt.setText(String.valueOf(redondear(s.getLq(), 4)));
            wTxt.setText(String.valueOf(redondear(s.getW(), 4)));
            wqTxt.setText(String.valueOf(redondear(s.getWq(), 4)));

            lambdaTxt.setText(String.valueOf(redondear(s.getLambda(), 2)));
            miuTxt.setText(String.valueOf(redondear(s.getMu(), 2)));

            if(!"".equals(tTxt.getText())){
                MM1Model mod = new MM1Model(Double.valueOf(lambdaTxt.getText()), Double.valueOf(miuTxt.getText()));
                Double W = redondear(mod.wt(Double.valueOf(lambdaTxt.getText()), Double.valueOf(miuTxt.getText()), Double.valueOf(tTxt.getText())), 5);
                wtTxt.setText(String.valueOf(W));
            }

            if(!"".equals(t2Txt.getText())){
                MM1Model mod = new MM1Model(Double.valueOf(lambdaTxt.getText()), Double.valueOf(miuTxt.getText()));

                Double Wq =redondear(mod.wqdet(Double.valueOf(lambdaTxt.getText()), Double.valueOf(miuTxt.getText()), Double.valueOf(t2Txt.getText())), 5);
                wqtTxt.setText(String.valueOf(Wq));
            }
        }
    }//GEN-LAST:event_simularBtnActionPerformed

    private void borrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrar1ActionPerformed
        cleanTxt();
    }//GEN-LAST:event_borrar1ActionPerformed

    private void lambdaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lambdaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lambdaTxtActionPerformed

    private void wqTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wqTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wqTxtActionPerformed

    private void tTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Simulado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Simulado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Simulado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Simulado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Simulado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LTxt;
    private javax.swing.JTextField LqTxt;
    private javax.swing.JButton borrar1;
    private javax.swing.JButton borrar3;
    private javax.swing.JButton borrar4;
    private javax.swing.JTextField efiTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField lambdaTxt;
    private javax.swing.JTextField miuTxt;
    private javax.swing.JButton reg;
    private javax.swing.JTextField rhoTxt;
    private javax.swing.JButton salir;
    private javax.swing.JButton simularBtn;
    private javax.swing.JTextField t2Txt;
    private javax.swing.JTextField tTxt;
    private javax.swing.JTextField wTxt;
    private javax.swing.JTextField wqTxt;
    private javax.swing.JTextField wqtTxt;
    private javax.swing.JTextField wtTxt;
    // End of variables declaration//GEN-END:variables

    private void centrarVentana() {
    setLocationRelativeTo(null);
    }
    
    public void transparenciaBotones(){
        
        /*simularBtn.setOpaque(false);
        simularBtn.setBorder(null);
         simularBtn.setContentAreaFilled(false);
        
        borrar1.setOpaque(false);
       borrar1.setBorder(null);
        borrar1.setContentAreaFilled(false);
        
          borrar2.setOpaque(false);
        borrar2.setBorder(null);
        borrar2.setContentAreaFilled(false);
        
        borrar3.setOpaque(false);
        borrar3.setBorder(null);
        borrar3.setContentAreaFilled(false);
        
        borrar4.setOpaque(false);
        borrar4.setBorder(null);
        borrar4.setContentAreaFilled(false);
        
        reg.setOpaque(false);
      reg.setBorder(null);
       reg.setContentAreaFilled(false);
       
         salir.setOpaque(false);
       salir.setBorder(null);
       salir.setContentAreaFilled(false);
       
   */
      
        
    }
    
     private boolean validacion()
    {
        if (!lambdaTxt.getText().isEmpty() && !miuTxt.getText().isEmpty())
        {
            if (Double.valueOf(lambdaTxt.getText()) < Double.valueOf(miuTxt.getText()))
            {
                return true;
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Lambda (λ) tiene que ser menor que Mi(μ).\nRevisar los parámetros ingresados", "ERROR",JOptionPane.ERROR_MESSAGE );
                return false;
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Los parámetros están incompletos.\nRevisar los valores introducidos de Lambda(λ)  y Miu (μ)", "ERROR",JOptionPane.ERROR_MESSAGE );
            return false;
        }
    }
     
     public double redondear(double numero, int decimales) {
        return Math.round(numero * Math.pow(10, decimales)) / Math.pow(10, decimales);
    }
      
      private void cleanTxt()
    {
        lambdaTxt.setText("");
        miuTxt.setText("");
        rhoTxt.setText("");
        efiTxt.setText("");
        LTxt.setText("");
        LqTxt.setText("");
        wTxt.setText("");
        wqTxt.setText("");
    }

}
