/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Aldemaro
 */
public class Visitante extends javax.swing.JFrame {

    /**
     * Creates new form Visitante
     */
    public Visitante() {
        super("DATOS DEL VISITANTE");
        initComponents();
        this.setDefaultCloseOperation(Visitante.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        txtNOMBREINST.setEnabled(false);
        btnEMPESAR.setEnabled(false);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNOMBRE = new javax.swing.JTextField();
        txtNOMBREINST = new javax.swing.JTextField();
        btnEMPESAR = new javax.swing.JButton();
        btnCANCELAR = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        btgIngresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtBOTELLAS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre :");

        jLabel2.setText("DATOS DEL VISITADOR");

        btnEMPESAR.setText("EMPESAR");
        btnEMPESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEMPESARActionPerformed(evt);
            }
        });

        btnCANCELAR.setText("CANCELAR");
        btnCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCANCELARActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione una Option", "Nombre de Universidad :", "Nombre de Intitucion :", "Nombre de Empresa :", "Nombre de Colegio :", "Nombre de Publico:" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btgIngresar.setText("INGRESAR DATOS");
        btgIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgIngresarActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero de Botellas a Procesar :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnCANCELAR)
                        .addGap(26, 26, 26)
                        .addComponent(btgIngresar)
                        .addGap(26, 26, 26)
                        .addComponent(btnEMPESAR)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNOMBREINST, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBOTELLAS, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNOMBREINST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBOTELLAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCANCELAR)
                    .addComponent(btgIngresar)
                    .addComponent(btnEMPESAR))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEMPESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEMPESARActionPerformed
        // TODO add your handling code here:
        String nom = txtNOMBRE.getText();
        int numBotella = Integer.parseInt(txtBOTELLAS.getText());
        Simulador obj = new Simulador(nom,numBotella);
        obj.setVisible(true);
        this.dispose();
        this.setDefaultCloseOperation(Visitante.EXIT_ON_CLOSE);
    }//GEN-LAST:event_btnEMPESARActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:       
        int var = jComboBox1.getSelectedIndex();
        if(var !=0)
            txtNOMBREINST.setEnabled(true);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btgIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgIngresarActionPerformed
        // TODO add your handling code here:
     
        String nomUni = txtNOMBREINST.getText();
        String nom = txtNOMBRE.getText();
        String SnumB = txtBOTELLAS.getText();
        if(!nom.isEmpty()){  
          if(!nomUni.isEmpty()){
              if(!SnumB.isEmpty()){
                  int num = Integer.parseInt(SnumB);
                  if(num >0){
                      btnEMPESAR.setEnabled(true);
                  }else{
                      JOptionPane.showMessageDialog(this, "Error el numero de botella debe ser mayor a cero");
                  }                  
              }else{
                 JOptionPane.showMessageDialog(this, "Error debe ingresar el numero de botella");
               }
          }else{
            JOptionPane.showMessageDialog(this, "Error debe ingresar el nombre del Lugar");
        } 
        }else{
            JOptionPane.showMessageDialog(this, "Error debe ingresar el nombre");
        }
    }//GEN-LAST:event_btgIngresarActionPerformed

    private void btnCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCANCELARActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCANCELARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visitante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visitante().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btgIngresar;
    private javax.swing.JButton btnCANCELAR;
    private javax.swing.JButton btnEMPESAR;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtBOTELLAS;
    private javax.swing.JTextField txtNOMBRE;
    private javax.swing.JTextField txtNOMBREINST;
    // End of variables declaration//GEN-END:variables
}
